[package]
name = "cvac"
version = "0.1.0"
authors = ["nguyenquannnn <nguyenquan233@gmail.com>"]
edition = "2018"
repository = "https://github.com/nguyenquannnn/CVaC"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
